baseURL = 'https://docs.tannerr.dev/'
title = 'my docs'
theme = 'hugo-book'
languageCode = 'en-us'

disableKinds = ['taxonomy', 'taxonomyTerm']

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  style = 'monokai'
  lineNos = true
  guessSyntax = true

[params]
  BookTheme = 'dark'
  BookSection = '*'
  BookSearch = true
  BookToC = true
